  MODULE('GEASYPOE001.CLW')
PresupuestosObrasElectricas PROCEDURE                 !PRESUPUESTO_OBRA_ELECTRICA
POE_Reporte            PROCEDURE                      !Print the PRESUPUESTO_OBRA_ELECTRICA File
SolicitudesObrasElectricas PROCEDURE                  !SOLICITUD_OBRA_ELECTRICA
SOE_Reporte            PROCEDURE                      !Print the SOLICITUD_OBRA_ELECTRICA File
TipoObra               PROCEDURE                      !TIPO_DE_OBRA
SOE_Browse             PROCEDURE                      !Select a SOLICITUD_OBRA_ELECTRICA Record
Presupuesto            PROCEDURE                      !Form PRESUPUESTO_OBRA_ELECTRICA
  END
